server:
  port: 8080
spring:
  profiles: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/usercenter
    username: postgres
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.postgresql.Driver
    druid:
      initial-size: 1
      min-idle: 5
      max-active: 5
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 'x'
      test-on-borrow: false
      test-while-idle: true
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
  servlet:
    multipart:
      max-file-size: 1000MB
  redis:
    host: 132.232.149.115
    database: 3
    password: crs-9lmnweit:i!jbEMgS%85nbuG
    port: 26379
    timeout: 5000
    lettuce:
      pool:
        max-active: 2
        min-idle: 0
        max-idle: 2

pagehelper:
  helperDialect: postgresql  # 分页插件会自动检测当前的数据库链接，自动选择合适的分页方式。 你可以配置helperDialect属性来指定分页插件使用哪种方言。
  reasonable: true      # 分页合理化参数，默认值为false。当该参数设置为 true 时，pageNum<=0 时会查询第一页，pageNum>pages（超过总数时），会查询最后一页。默认false 时，直接根据参数进行查询。
  supportMethodsArguments: true # 支持通过 Mapper 接口参数来传递分页参数，默认值false，分页插件会从查询方法的参数值中，自动根据上面 params 配置的字段中取值，查找到合适的值时就会自动分页。
  params: count=countSql

logging:
  config: classpath:log4j2-dev.xml

mybatis:
  mapper-locations: classpath:sql-mapping/*.xml
